import * as XLSX from 'xlsx';
import type {CargoItem,LoadingCalculation,ConsolidationOption} from '../types';
import {blankCargo} from '../data/seed';
import {validateCargo} from './packing';
const columns=['Номер заявки','Наименование ТМЗ','Количество','Длина','Ширина','Высота','Вес','Штабелирование','Количество ярусов','Не кантовать','Город отправления','Город назначения','Дата отправки'];
const yes=(x:unknown)=>['да','yes','true','1'].includes(String(x).trim().toLowerCase());
function booleanCell(x:unknown,label:string){if(!['да','нет','yes','no','true','false','1','0'].includes(String(x).trim().toLowerCase()))throw Error(`${label}: укажите Да или Нет`);return yes(x);}
function dateCell(x:unknown){if(typeof x==='number'){const d=XLSX.SSF.parse_date_code(x);if(!d)throw Error('Некорректная дата');return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`;}const s=String(x??'').trim();const m=s.match(/^(\d{2})\.(\d{2})\.(\d{4})$/);const d=m?`${m[3]}-${m[2]}-${m[1]}`:s;if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||new Date(d).toISOString().slice(0,10)!==d)throw Error('Дата должна быть в формате ГГГГ-ММ-ДД');return d;}
export function cargoToRows(cargo:CargoItem[]){return cargo.map(c=>({'Номер заявки':c.requestId,'Наименование ТМЗ':c.name,'Количество':c.quantity,'Длина':c.length,'Ширина':c.width,'Высота':c.height,'Вес':c.weight,'Штабелирование':c.stackable?'Да':'Нет','Количество ярусов':c.maxLayers,'Не кантовать':c.tiltable?'Нет':'Да','Город отправления':c.origin,'Город назначения':c.destination,'Дата отправки':c.date,'Подразделение':c.customer,'Можно поворачивать':c.rotatable?'Да':'Нет','Хрупкий':c.fragile?'Да':'Нет','Только вертикально':c.upright?'Да':'Нет','Особые условия':c.notes,'Объём позиции, м³':c.length*c.width*c.height*c.quantity,'Вес позиции, кг':c.weight*c.quantity}));}
export function parseExcel(buffer:ArrayBuffer):CargoItem[]{const wb=XLSX.read(buffer,{type:'array'});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!rows.length)throw Error('В файле нет строк с грузом');const missing=columns.filter(c=>!(c in rows[0]));if(missing.length)throw Error(`Отсутствуют колонки: ${missing.join(', ')}`);
 const result=rows.map((r,i)=>{try{const n=(k:string)=>Number(String(r[k]).replace(',','.'));const tiltable=!booleanCell(r['Не кантовать'],'Не кантовать');const c:CargoItem={...blankCargo(),requestId:String(r['Номер заявки']).trim(),name:String(r['Наименование ТМЗ']).trim(),quantity:n('Количество'),length:n('Длина'),width:n('Ширина'),height:n('Высота'),weight:n('Вес'),stackable:booleanCell(r['Штабелирование'],'Штабелирование'),maxLayers:n('Количество ярусов'),tiltable,upright:r['Только вертикально']!==undefined?booleanCell(r['Только вертикально'],'Только вертикально'):!tiltable,rotatable:r['Можно поворачивать']!==undefined?booleanCell(r['Можно поворачивать'],'Можно поворачивать'):true,fragile:r['Хрупкий']!==undefined?booleanCell(r['Хрупкий'],'Хрупкий'):false,origin:String(r['Город отправления']).trim(),destination:String(r['Город назначения']).trim(),date:dateCell(r['Дата отправки']),customer:String(r['Подразделение']||'Импорт Excel'),notes:String(r['Особые условия']??(tiltable?'':'Не кантовать'))};const errors=validateCargo(c);if(!c.requestId||!c.origin||!c.destination)errors.push('Укажите заявку и маршрут');if(errors.length)throw Error(errors.join('; '));return c;}catch(e){throw Error(`Строка ${i+2}: ${(e as Error).message}`);}});return result;
}
function sheet(wb:XLSX.WorkBook,name:string,rows:object[]){const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=Array.from({length:30},()=>({wch:24}));XLSX.utils.book_append_sheet(wb,ws,name);}
export function exportCargo(cargo:CargoItem[]){const wb=XLSX.utils.book_new();sheet(wb,'ТМЗ',cargoToRows(cargo));XLSX.writeFile(wb,'ТМЗ.xlsx');}
export function exportCalculation(c:LoadingCalculation,options:ConsolidationOption[]){const wb=XLSX.utils.book_new();sheet(wb,'ТМЗ',cargoToRows(c.cargo));sheet(wb,'Автомобиль',[{Тип:c.vehicle.name,'Длина, м':c.vehicle.length,'Ширина, м':c.vehicle.width,'Высота, м':c.vehicle.height,'Грузоподъёмность, кг':c.vehicle.capacity,'Объём, м³':c.vehicle.length*c.vehicle.width*c.vehicle.height,'Нагрузка пола, кг/м²':c.vehicle.maxFloorLoad}]);sheet(wb,'Расчёт',[{Номер:c.id,Дата:c.date,Мест:c.result.count,'Объём, м³':c.result.volume,'Вес, кг':c.result.weight,'Площадь пола, м²':c.result.floor,'Загрузка объёма, %':c.result.volumePercent,'Загрузка веса, %':c.result.weightPercent,'Загрузка пола, %':c.result.floorPercent,'Итоговая загрузка, %':c.result.utilization,'Стоимость, ₸':c.cost,'Экономия, ₸':c.savings,Статус:c.result.status,Рекомендации:c.result.reasons.join('; ')||c.result.status}]);sheet(wb,'Схема',c.result.positions.map(p=>({ТМЗ:c.cargo.find(x=>x.id===p.cargoId)?.name,'X, м':p.x,'Y, м':p.y,'Длина, м':p.length,'Ширина, м':p.width,'Высота места, м':p.height,Ярусы:p.layers,'Первое место':p.first})));sheet(wb,'Консолидация',options.map(o=>({Заявки:o.requests.join(' + '),Маршрут:o.route,Автомобиль:o.vehicle.name,'Отдельно, ₸':o.separate,'Вместе, ₸':o.cost,'Экономия, ₸':o.savings,'Экономия, %':o.savingsPercent})));XLSX.writeFile(wb,`${c.id}.xlsx`);}
