import {describe,it,expect} from 'vitest';
import {createSeed,vehicles,blankCargo} from '../data/seed';
import {calculateVehicleUtilization,generateLoadingPlan,isValidPosition,checkCargoFits,orientations,calculateStacking} from './packing';
import {findOptimalVehicle,calculateConsolidation,calculateTransportCost,calculateSavings} from './transport';
import {validateData} from '../hooks/useStorage';
import {parseExcel,cargoToRows} from './excel';
import * as XLSX from 'xlsx';
const base=()=>({...blankCargo(),name:'Груз',requestId:'101'});
describe('Physical loading',()=>{
 it('20t truck volume equals 89.964; cable has 10 supported stacks',()=>{const v=vehicles[3];expect(v.length*v.width*v.height).toBeCloseTo(89.964,3);const r=calculateVehicleUtilization([{...base(),quantity:20}],v);expect(r.fits).toBe(true);expect(r.volume).toBeCloseTo(19.2);expect(r.weight).toBe(5000);expect(r.floor).toBeCloseTo(9.6);expect(r.positions).toHaveLength(10);expect(r.positions.every(p=>p.layers===2)).toBe(true);});
 it('does not accept low volume cargo exceeding length',()=>{const r=calculateVehicleUtilization([{...base(),length:14,width:.1,height:.1,rotatable:false}],vehicles[3]);expect(r.volumePercent).toBeLessThan(1);expect(r.fits).toBe(false);expect(r.reasons.join()).toContain('длины');});
 it('weight excess is rejected even with a valid geometric plan',()=>{const r=calculateVehicleUtilization([{...base(),weight:1600}],vehicles[0]);expect(r.fits).toBe(false);expect(r.reasons.join()).toContain('грузоподъёмность');});
 it('respects rotations and upright restrictions',()=>{const c={...base(),length:1.9,width:3,rotatable:false};expect(checkCargoFits([c],vehicles[0])).toBe(false);expect(checkCargoFits([{...c,rotatable:true}],vehicles[0])).toBe(true);const tall={...base(),height:3,tiltable:true,upright:true,notes:''};expect(checkCargoFits([tall],vehicles[0])).toBe(false);expect(checkCargoFits([{...tall,upright:false}],vehicles[0])).toBe(true);});
 it('all six orientations available when all rotations enabled',()=>{expect(orientations({...base(),length:1,width:2,height:3,tiltable:true,upright:false,notes:''})).toHaveLength(6);});
 it('no stacking and fragile override tiers; body height limits tiers',()=>{expect(calculateStacking({...base(),fragile:true,maxLayers:5},vehicles[3])).toBe(1);expect(calculateStacking({...base(),stackable:false},vehicles[3])).toBe(1);expect(calculateStacking({...base(),maxLayers:10},vehicles[3])).toBe(2);});
 it('floor pressure can reduce layers or reject a place',()=>{const v={...vehicles[3],maxFloorLoad:300};const r=calculateVehicleUtilization([{...base(),quantity:2}],v);expect(r.fits).toBe(true);expect(r.positions.every(p=>p.layers===1)).toBe(true);expect(checkCargoFits([{...base(),weight:500}],v)).toBe(false);});
 it('nonstackable large footprints cannot fit despite spare volume',()=>{const r=calculateVehicleUtilization([{...base(),length:4,width:2,height:.1,quantity:5,stackable:false}],vehicles[3]);expect(r.fits).toBe(false);expect(r.volumePercent).toBeLessThan(10);expect(r.reasons.join()).toContain('площади пола');});
 it('non overlapping mixed cargo plans remain within bounds',()=>{const d=createSeed();for(const v of d.vehicles){const p=generateLoadingPlan(d.cargo,v);for(const item of p)expect(isValidPosition(item,p,v)).toBe(true);for(const c of d.cargo)expect(p.filter(x=>x.cargoId===c.id).reduce((s,x)=>s+x.layers,0)).toBeLessThanOrEqual(c.quantity);}});
 it('rejects overlaps and out of bounds for manual edits',()=>{const v=vehicles[3],p=generateLoadingPlan([{...base(),quantity:4}],v);expect(isValidPosition({...p[0],x:-.1},p,v)).toBe(false);expect(isValidPosition({...p[0],x:p[1].x,y:p[1].y},p,v)).toBe(false);});
 it('invalid dimensions rejected and empty result neutral',()=>{expect(checkCargoFits([{...base(),length:0}],vehicles[3])).toBe(false);expect(calculateVehicleUtilization([],vehicles[3]).status).toBe('Нет данных');});
 it('status boundaries 50, 70, 90 and above 90 percent',()=>{for(const [load,tone] of [[49,'low'],[50,'reserve'],[70,'success'],[90,'success'],[91,'warning'],[100,'warning']] as const){const v={...vehicles[3],maxFloorLoad:100000};const c={...base(),length:1,width:1,height:1,quantity:1,weight:v.capacity*load/100};expect(calculateVehicleUtilization([c],v).tone).toBe(tone);}});
});
describe('Costs and consolidation',()=>{
 it('chooses smallest feasible or cheapest feasible transport',()=>{const cargo=[{...base(),quantity:20}];expect(findOptimalVehicle(cargo,vehicles,[],600,'size').find(x=>x.result.fits)?.vehicle.id).toBe('v2');expect(findOptimalVehicle(cargo,vehicles,[],600).find(x=>x.result.fits)?.vehicle.id).toBe('v2');});
 it('uses effective latest carrier tariff and minimum',()=>{const v=vehicles[0];const t={id:'1',carrier:'A',origin:'A',destination:'B',vehicleId:v.id,fixed:100,perKm:2,minimum:150,validFrom:'2026-01-01'};expect(calculateTransportCost(v,10,[t],'A','B','2026-02-01')).toBe(150);expect(calculateTransportCost(v,100,[t,{...t,id:'2',fixed:500,validFrom:'2026-03-01'}],'A','B','2026-04-01')).toBe(700);expect(calculateTransportCost(v,100,[t,{...t,id:'2',fixed:500,validFrom:'2026-03-01'}],'A','B','2026-02-01')).toBe(300);});
 it('savings example equals 170000 and approximately 37%',()=>{const s=calculateSavings(460000,290000);expect(s.savings).toBe(170000);expect(s.savingsPercent).toBeCloseTo(36.9565,3);});
 it('seed has 18 cargo, 10 requests, 5 vehicles and feasible options',()=>{const d=createSeed();expect(d.cargo).toHaveLength(18);expect(new Set(d.cargo.map(c=>c.requestId)).size).toBe(10);expect(d.vehicles).toHaveLength(5);const o=calculateConsolidation(d.cargo,d.vehicles,d.tariffs,d.settings);expect(o.length).toBeGreaterThan(0);for(const x of o){expect(x.result.fits).toBe(true);expect(x.savings).toBeGreaterThan(0);expect(x.cost).toBeLessThan(x.separate);}});
 it('different origins and incompatible dates cannot combine',()=>{const d=createSeed();const a={...base(),id:'a',origin:'A',destination:'B',date:'2026-09-01'},b={...a,id:'b',requestId:'102',origin:'C'};expect(calculateConsolidation([a,b],vehicles,[],d.settings)).toHaveLength(0);expect(calculateConsolidation([a,{...b,origin:'A',date:'2026-09-20'}],vehicles,[],d.settings)).toHaveLength(0);});
 it('unknown nearby route rejected; configured deviation allowed only within limit',()=>{const d=createSeed(),a={...base(),id:'a',destination:'Астана'},b={...a,id:'b',requestId:'102',destination:'Караганда'};expect(calculateConsolidation([a,b],vehicles,[],{...d.settings,maxDeviation:0})).toHaveLength(0);expect(calculateConsolidation([a,b],vehicles,[],{...d.settings,maxDeviation:250}).length).toBeGreaterThan(0);});
});
describe('Import and persistence',()=>{
 it('JSON round trip retains all data and plan',()=>{const d=createSeed();d.manual=generateLoadingPlan([d.cargo[0]],d.vehicles[3]);const restored=JSON.parse(JSON.stringify(d));expect(validateData(restored)).toBe(true);expect(restored).toEqual(d);expect(validateData({})).toBe(false);});
 it('xlsx import/export preserves geometry and constraints',()=>{const d=createSeed(),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(cargoToRows(d.cargo)),'ТМЗ');const rows=parseExcel(XLSX.write(wb,{type:'array',bookType:'xlsx'}));expect(rows).toHaveLength(18);for(let i=0;i<18;i++){expect({...rows[i],id:''}).toEqual({...d.cargo[i],id:''});}});
 it('malformed xlsx fails before returning any rows',()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{'Название':'test'}]),'ТМЗ');expect(()=>parseExcel(XLSX.write(wb,{type:'array',bookType:'xlsx'}))).toThrow('Отсутствуют колонки');});
});

