import {Button} from '@mui/material';
import {ArrowRight,Plus,ArrowUpRight,Package,Truck,Weight,Box,TrendingDown} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,AreaChart,Area,Legend} from 'recharts';
import type {AppData,ConsolidationOption} from '../types';
import {calculateKPI,requestsFromCargo} from '../services/transport';
import {calculateCargoVolume,calculateCargoWeight} from '../services/packing';
import {fmt,money,today} from '../utils/format';
export default function Dashboard({data,options,onNavigate,analytics=false}:{data:AppData;options:ConsolidationOption[];onNavigate:(page:number)=>void;analytics?:boolean}){const kpi=calculateKPI(data.history),requests=requestsFromCargo(data.cargo);const flights=data.history.filter(h=>h.result.fits);const vehicleLoads=data.vehicles.map(v=>{const rows=flights.filter(h=>h.vehicle.id===v.id);return {name:v.name.replace(' / Еврофура','').replace('Еврофура High Cube','High Cube'),Загрузка:rows.length?Math.round(rows.reduce((s,h)=>s+h.result.utilization,0)/rows.length):0};});const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const rows=flights.filter(h=>h.date.slice(0,7)===d.toISOString().slice(0,7));return {name:d.toLocaleDateString('ru-RU',{month:'short'}),'Расходы':rows.reduce((s,h)=>s+h.cost,0),'Без консолидации':rows.reduce((s,h)=>s+h.baseline,0)};});
 const stats=analytics?[['Средняя загрузка',`${fmt(kpi.averageLoad)}%`,'По сохранённым рейсам',Truck],['Доля недогруженных',`${fmt(kpi.underloaded)}%`,'Загрузка менее 50%',Box],['Оптимальная загрузка',`${fmt(kpi.optimal)}%`,'От 70 до 90%',Weight],['Экономия',money(kpi.savings),`${fmt(kpi.baseline?kpi.savings/kpi.baseline*100:0)}% от исходной стоимости`,TrendingDown]]:[['Заявок сегодня',String(requests.filter(r=>r.date===today()).length),`${requests.length} всего в работе`,Package],['Общий вес',`${fmt(data.cargo.reduce((s,c)=>s+calculateCargoWeight(c),0)/1000)} т`,`${data.cargo.length} позиций ТМЗ`,Weight],['Общий объём',`${fmt(data.cargo.reduce((s,c)=>s+calculateCargoVolume(c),0))} м³`,'По всем текущим заявкам',Box],['Машин запланировано',String(flights.length),`${fmt(kpi.averageLoad)}% средняя загрузка`,Truck]];
 return <><div className="page-heading"><div><div className="eyebrow">{analytics?'ЭФФЕКТИВНОСТЬ ЛОГИСТИКИ':'ОБЗОР ПЕРЕВОЗОК'}</div><h1>{analytics?'Аналитика перевозок':'Всё под контролем.'}</h1><p>{analytics?'Показатели рассчитаны по сохранённым успешным рейсам.':'Загрузка транспорта, заявки и возможности для экономии.'}</p></div><Button variant="contained" startIcon={<Plus size={18}/>} onClick={()=>onNavigate(1)}>Новый расчёт</Button></div><div className="stats">{stats.map(([label,n,detail,Icon])=>{const I=Icon as typeof Truck;return <div className="stat" key={String(label)}><div className="stat-top"><span>{String(label)}</span><I size={18}/></div><strong>{String(n)}</strong><small>{String(detail)}</small></div>})}</div>
 {!analytics&&<div className="opportunity"><div className="opportunity-icon"><TrendingDown/></div><div><span className="eyebrow">ВОЗМОЖНОСТЬ ДЛЯ ЭКОНОМИИ</span><h3>{options.length?`До ${money(options[0].savings)} на одном объединённом рейсе`:'Проверьте возможности консолидации'}</h3><p>{options.length?`Найдено ${options.length} вариантов. Сравните совместимые заявки и выберите подходящий.`:'Добавьте заявки с совместимыми маршрутами и датами.'}</p></div><Button endIcon={<ArrowRight size={16}/>} onClick={()=>onNavigate(5)}>Посмотреть варианты</Button></div>}
 <div className="charts-grid"><section className="panel"><div className="panel-heading"><h2>Загрузка автомобилей</h2><span className="subtle-chip">Среднее, %</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={vehicleLoads} barSize={34}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e9eef0"/><XAxis dataKey="name" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis domain={[0,100]} tick={{fontSize:11}} axisLine={false} tickLine={false} unit="%"/><Tooltip formatter={v=>`${v}%`}/><Bar dataKey="Загрузка" fill="#32997d" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="panel"><div className="panel-heading"><h2>Расходы на перевозки</h2><span className="subtle-chip">6 месяцев · ₸</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={months}><defs><linearGradient id="expense" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4e9f8a" stopOpacity={.2}/><stop offset="100%" stopColor="#4e9f8a" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e9eef0"/><XAxis dataKey="name" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${v/1000}к`} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))}/><Area dataKey="Расходы" type="monotone" stroke="#328f77" fill="url(#expense)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section></div>
 {analytics?<><div className="stats">{[['Стоимость 1 кг',money(kpi.weight?kpi.cost/kpi.weight:0)],['Стоимость 1 м³',money(kpi.volume?kpi.cost/kpi.volume:0)],['Заявок на машину',fmt(kpi.requestsPerVehicle)],['Стоимость перевозок',money(kpi.cost)]].map(([l,n])=><div className="stat" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><section className="panel"><h2>Эффект консолидации</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={months}><XAxis dataKey="name"/><YAxis tickFormatter={v=>`${v/1000}к`}/><Tooltip formatter={v=>money(Number(v))}/><Legend/><Bar dataKey="Без консолидации" fill="#c9d5d7"/><Bar dataKey="Расходы" fill="#32997d"/></BarChart></ResponsiveContainer></div></section></>:<><section className="panel table-panel"><div className="panel-heading"><div><h2>Заявки в работе <span className="count-chip">{requests.length}</span></h2><p className="panel-subtitle">Планируйте рейсы и объединяйте грузы</p></div><Button size="small" endIcon={<ArrowUpRight size={15}/>} onClick={()=>onNavigate(2)}>Все ТМЗ</Button></div><div className="table-scroll"><table><thead><tr><th>Заявка</th><th>Маршрут</th><th>Дата отправки</th><th>Вес</th><th>Объём</th><th>Позиций</th></tr></thead><tbody>{requests.slice(0,6).map(r=><tr key={r.id}><td><strong>№{r.id}</strong></td><td>{r.origin}<span className="route-arrow">→</span>{r.destination}</td><td>{r.date.split('-').reverse().join('.')}</td><td>{fmt(r.cargo.reduce((s,c)=>s+calculateCargoWeight(c),0))} кг</td><td>{fmt(r.cargo.reduce((s,c)=>s+calculateCargoVolume(c),0))} м³</td><td><span className="subtle-chip">{r.cargo.length} ТМЗ</span></td></tr>)}</tbody></table></div></section><div className="mini-kpis"><span>Стоимость рейсов <strong>{money(kpi.cost)}</strong></span><span>Экономия <strong>{money(kpi.savings)}</strong></span><span>Недогруженных машин <strong>{flights.filter(h=>h.result.utilization<50).length}</strong></span></div></>}
 {data.history.some(h=>h.demo)&&<p className="footnote">В истории присутствуют демонстрационные рейсы. Их можно удалить в разделе «История расчётов».</p>}</>;
}
