import {useRef,useState} from 'react';
import {Button,Alert} from '@mui/material';
import {RotateCw,RefreshCw,Move} from 'lucide-react';
import type {CargoItem,LoadingPosition,Vehicle} from '../types';
import {isValidPosition} from '../services/packing';
import {fmt} from '../utils/format';
export const colors=['#5fae95','#769fcd','#d5aa62','#9e8cc5','#db8f81','#72b2b8','#a5b476','#c898af'];
export default function LoadingPlan({cargo,vehicle,positions,onChange,onReset,compact=false}:{cargo:CargoItem[];vehicle:Vehicle;positions:LoadingPosition[];onChange?:(p:LoadingPosition[])=>void;onReset?:()=>void;compact?:boolean}){const ref=useRef<SVGSVGElement>(null);const [selected,setSelected]=useState<string|null>(null);const [drag,setDrag]=useState<{id:string;dx:number;dy:number}|null>(null);const [ghost,setGhost]=useState<LoadingPosition|null>(null);const [message,setMessage]=useState('');
 function point(e:React.PointerEvent){const svg=ref.current!;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM()!.inverse());}
 function rotate(){const p=positions.find(p=>p.id===selected);if(!p)return;const c=cargo.find(c=>c.id===p.cargoId)!;if(!c.rotatable){setMessage('Поворот этой позиции запрещён');return;}const next={...p,length:p.width,width:p.length};if(!isValidPosition(next,positions,vehicle)){setMessage('Поворот невозможен: пересечение или граница кузова');return;}onChange?.(positions.map(x=>x.id===p.id?next:x));setMessage('');}
 const current=positions.find(p=>p.id===selected);return <section className="panel loading-panel"><div className="panel-heading"><div><h2>Схема загрузки</h2><p className="panel-subtitle">Вид сверху · {fmt(vehicle.length)} × {fmt(vehicle.width)} м</p></div>{!compact&&<div className="actions"><Button size="small" startIcon={<RotateCw size={15}/>} disabled={!current||!onChange} onClick={rotate}>Повернуть</Button><Button size="small" startIcon={<RefreshCw size={15}/>} onClick={()=>{onReset?.();setSelected(null);setMessage('')}}>Пересчитать размещение</Button></div>}</div>
 <div className="plan-scroll"><div className="plan-shell"><div className="dimension">← {fmt(vehicle.length)} м →</div><svg ref={ref} viewBox={`-0.04 -0.04 ${vehicle.length+.08} ${vehicle.width+.08}`} role="img" aria-label={`Схема кузова ${vehicle.name}: ${positions.length} штабелей`} className="truck-plan" style={{aspectRatio:`${vehicle.length}/${vehicle.width}`,minHeight:compact?100:150}} onPointerMove={e=>{if(!drag)return;const pt=point(e);const p=positions.find(p=>p.id===drag.id)!;setGhost({...p,x:Math.round((pt.x-drag.dx)*100)/100,y:Math.round((pt.y-drag.dy)*100)/100});}} onPointerUp={()=>{if(ghost){if(isValidPosition(ghost,positions,vehicle)){onChange?.(positions.map(p=>p.id===ghost.id?ghost:p));setMessage('');}else setMessage('Перемещение отменено: груз пересекается с другим или выходит за границы кузова');}setDrag(null);setGhost(null);}} onPointerCancel={()=>{setDrag(null);setGhost(null);}}>
 <rect x={0} y={0} width={vehicle.length} height={vehicle.width} fill="#f4f8f7" stroke="#8daba4" strokeWidth={.025}/>
 {Array.from({length:Math.floor(vehicle.length)},(_,i)=><line key={i} x1={i+1} x2={i+1} y1={0} y2={vehicle.width} stroke="#dce8e4" strokeWidth={.01} strokeDasharray=".04 .04"/>)}
 {positions.map(p=>{const c=cargo.find(c=>c.id===p.cargoId);if(!c)return null;const color=colors[cargo.indexOf(c)%colors.length];return <g key={p.id} tabIndex={onChange?0:undefined} role={onChange?'button':undefined} aria-label={`${c.name}, места ${p.first}–${p.first+p.layers-1}. Стрелки перемещают, R поворачивает.`} className={onChange?'movable':''} onFocus={()=>setSelected(p.id)} onKeyDown={e=>{if(!onChange)return;if(e.key.toLowerCase()==='r'){rotate();return;}const dx=e.key==='ArrowRight'?.05:e.key==='ArrowLeft'?-.05:0,dy=e.key==='ArrowDown'?.05:e.key==='ArrowUp'?-.05:0;if(!dx&&!dy)return;e.preventDefault();const next={...p,x:p.x+dx,y:p.y+dy};if(isValidPosition(next,positions,vehicle))onChange(positions.map(q=>q.id===p.id?next:q));else setMessage('Граница кузова или пересечение');}} onPointerDown={e=>{if(!onChange)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setSelected(p.id);const pt=point(e);setDrag({id:p.id,dx:pt.x-p.x,dy:pt.y-p.y});}}>
 <title>{`${c.name}\n${fmt(p.length)} × ${fmt(p.width)} × ${fmt(p.height)} м\n${fmt(p.weight)} кг · заявка №${c.requestId}\n${p.layers} мест / ярусов\nШтабелирование: ${c.stackable?'да':'нет'}\n${c.notes}`}</title><rect x={p.x+.015} y={p.y+.015} width={Math.max(.001,p.length-.03)} height={Math.max(.001,p.width-.03)} rx={.035} fill={color} fillOpacity={.30} stroke={selected===p.id?'#173e35':color} strokeWidth={selected===p.id?.035:.016}/><text x={p.x+p.length/2} y={p.y+p.width/2-.035} textAnchor="middle" fontSize={Math.min(.12,p.length*.14,p.width*.17)} fill="#28554b" pointerEvents="none">{c.name.length>15?c.name.slice(0,13)+'…':c.name}<tspan x={p.x+p.length/2} dy={.16} fontSize=".105">{p.first}–{p.first+p.layers-1} · {p.layers} яр.</tspan></text></g>})}
 {ghost&&<rect x={ghost.x} y={ghost.y} width={ghost.length} height={ghost.width} fill={isValidPosition(ghost,positions,vehicle)?'#147d6460':'#e84c4c60'} stroke="#174d40" strokeWidth={.025} pointerEvents="none"/>}</svg><div className="doors">ДВЕРИ →</div></div></div>
 <div className="legend">{cargo.filter(c=>positions.some(p=>p.cargoId===c.id)).map(c=><span key={c.id}><i style={{background:colors[cargo.indexOf(c)%colors.length]}}/>{c.name}</span>)}</div>{!compact&&<><div className="plan-help"><Move size={14}/> Перетаскивайте штабели мышью. Для клавиатуры: Tab, стрелки и R. Штабели перемещаются целиком.</div>{current&&<div className="selection-info">Выбрано: {cargo.find(c=>c.id===current.cargoId)?.name} · X {fmt(current.x,2)} м · Y {fmt(current.y,2)} м · {current.layers} яр. · {fmt(current.weight)} кг</div>}<p className="footnote">Упрощённая схема: одинаковые места в штабеле, полная опора. Осевые нагрузки, крепление и порядок выгрузки требуют проверки логиста. «Возле дверей» — предпочтение размещения.</p></>}{message&&<Alert severity="warning" onClose={()=>setMessage('')}>{message}</Alert>}{!positions.length&&<div className="empty">Нет размещённых грузовых мест</div>}</section>;
}
