import {useState,useMemo,useRef,useEffect} from 'react';
import {Button,TextField,MenuItem,Alert,Snackbar,IconButton,Dialog,DialogTitle,DialogContent,DialogActions,Checkbox,FormControlLabel} from '@mui/material';
import {Truck,LayoutDashboard,Calculator,Package,Layers,Combine,Wallet,History,ChartNoAxesCombined,Settings,Plus,Download,Upload,Save,Printer,Search,ArrowRight,Copy,Trash2,Pencil,Sparkles} from 'lucide-react';
import type {AppData,CargoItem,Vehicle,Tariff,LoadingCalculation,ConsolidationOption} from './types';
import {useStorage,STORAGE_KEY,validateData} from './hooks/useStorage';
import {blankCargo} from './data/seed';
import {calculateVehicleUtilization,validateCargo,validateVehicle} from './services/packing';
import {findOptimalVehicle,calculateTransportCost,calculateConsolidation} from './services/transport';
import {parseExcel,exportCargo,exportCalculation} from './services/excel';
import {fmt,money,uid,today} from './utils/format';
import Editor,{cargoFields,vehicleFields,type Field} from './components/Editor';
import CargoTable from './components/CargoTable';
import LoadingPlan from './components/LoadingPlan';
import Summary from './components/Summary';
import Dashboard from './pages/Dashboard';
import SettingsPage from './pages/Settings';
const navigation=['Главная','Новый расчёт','ТМЗ','Автомобили','Схема загрузки','Консолидация заявок','Тарифы','История расчётов','Аналитика','Настройки'];
const navIcons=[LayoutDashboard,Calculator,Package,Truck,Layers,Combine,Wallet,History,ChartNoAxesCombined,Settings];
type EditorState={kind:'cargo'|'vehicle'|'tariff';value:CargoItem|Vehicle|Tariff};
export default function App(){const {data,update,storageError}=useStorage();const [page,setPage]=useState(0),[search,setSearch]=useState(''),[toast,setToast]=useState(''),[editor,setEditor]=useState<EditorState|null>(null),[confirm,setConfirm]=useState<{title:string;action:()=>void}|null>(null),[historyFilter,setHistoryFilter]=useState('all'),[sort,setSort]=useState('new'),[picked,setPicked]=useState(false),[onlySelected,setOnlySelected]=useState(false),[pendingOption,setPendingOption]=useState<ConsolidationOption|null>(null),[historyFrom,setHistoryFrom]=useState(''),[historyTo,setHistoryTo]=useState('');
 const excelInput=useRef<HTMLInputElement>(null),backupInput=useRef<HTMLInputElement>(null);
 const selected=useMemo(()=>data.cargo.filter(c=>data.selected.includes(c.id)),[data.cargo,data.selected]);const vehicle=data.vehicles.find(v=>v.id===data.vehicleId)??data.vehicles[0];
 const result=useMemo(()=>calculateVehicleUtilization(selected,vehicle,data.manual),[selected,vehicle,data.manual]);
 const options=useMemo(()=>calculateConsolidation(data.cargo,data.vehicles,data.tariffs,data.settings),[data.cargo,data.vehicles,data.tariffs,data.settings]);
 const comparisons=useMemo(()=>findOptimalVehicle(selected,data.vehicles,data.tariffs,data.settings.distance),[selected,data.vehicles,data.tariffs,data.settings.distance]);
 const applicable=pendingOption&&pendingOption.vehicle.id===vehicle.id&&pendingOption.cargo.length===selected.length&&pendingOption.cargo.every(c=>selected.some(s=>s.id===c.id&&JSON.stringify(s)===JSON.stringify(c)))?pendingOption:null;
 const cost=applicable?.cost??calculateTransportCost(vehicle,data.settings.distance,data.tariffs,selected[0]?.origin,selected[0]?.destination,selected[0]?.date);
 const navigate=(n:number)=>{setPage(n);setSearch('');};
 const mutate=(fn:(d:AppData)=>AppData)=>{setPendingOption(null);update(d=>({...fn(d),manual:null}));};
 const newCargo=()=>setEditor({kind:'cargo',value:blankCargo()});
 const editCargo=(c:CargoItem)=>setEditor({kind:'cargo',value:c});
 const copyCargo=(c:CargoItem)=>{mutate(d=>({...d,cargo:[...d.cargo,{...c,id:uid(),name:c.name+' (копия)'}]}));setToast('Позиция скопирована');};
 const deleteCargo=(c:CargoItem)=>setConfirm({title:`Удалить «${c.name}» из справочника и текущего расчёта?`,action:()=>mutate(d=>({...d,cargo:d.cargo.filter(x=>x.id!==c.id),selected:d.selected.filter(id=>id!==c.id)}))});
 function snapshot():LoadingCalculation{return {id:`LP-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,date:new Date().toISOString(),cargo:structuredClone(selected),vehicle:structuredClone(vehicle),result:structuredClone(result),cost,savings:applicable?.savings??0,baseline:applicable?.separate??cost,distance:applicable?.distance??data.settings.distance};}
 function saveCalculation(){if(!selected.length){setToast('Выберите хотя бы одну позицию');return;}const calc=snapshot();update(d=>({...d,history:[calc,...d.history]}));setToast(`Расчёт ${calc.id} сохранён`);}
 function chooseVehicle(mode:'size'|'cost'){const best=findOptimalVehicle(selected,data.vehicles,data.tariffs,data.settings.distance,mode).find(x=>x.result.fits);setPicked(true);if(best){mutate(d=>({...d,vehicleId:best.vehicle.id}));setToast(`Рекомендуется ${best.vehicle.name} · ${money(best.cost)}`);}else setToast('Подходящая машина не найдена. Проверьте причины в сравнении автомобилей.');}
 function saveEditor(value:any){if(!editor)return;const kind=editor.kind;mutate(d=>{if(kind==='cargo'){const exists=d.cargo.some(c=>c.id===value.id);return {...d,cargo:exists?d.cargo.map(c=>c.id===value.id?value:c):[...d.cargo,value],selected:page===1&&!exists?[...d.selected,value.id]:d.selected};}if(kind==='vehicle')return {...d,vehicles:d.vehicles.some(v=>v.id===value.id)?d.vehicles.map(v=>v.id===value.id?value:v):[...d.vehicles,value]};return {...d,tariffs:d.tariffs.some(t=>t.id===value.id)?d.tariffs.map(t=>t.id===value.id?value:t):[...d.tariffs,value]};});setEditor(null);setToast('Изменения сохранены');}
 const tariffFields:Field[]=[{key:'carrier',label:'Перевозчик',required:true},{key:'vehicleId',label:'Тип автомобиля',type:'select',options:data.vehicles.map(v=>({value:v.id,label:v.name})),required:true},{key:'origin',label:'Отправление',required:true},{key:'destination',label:'Назначение',required:true},{key:'fixed',label:'Фиксированная стоимость, ₸',type:'number'},{key:'perKm',label:'Стоимость 1 км, ₸',type:'number'},{key:'minimum',label:'Минимальный тариф, ₸',type:'number'},{key:'validFrom',label:'Действует с',type:'date',required:true}];
 function loadHistory(h:LoadingCalculation){mutate(d=>{const rows=h.cargo.map(c=>({...c,id:uid()}));const v={...h.vehicle,id:uid()};return {...d,cargo:[...d.cargo,...rows],selected:rows.map(c=>c.id),vehicles:[...d.vehicles,v],vehicleId:v.id,settings:{...d.settings,distance:h.distance}};});navigate(1);setPicked(false);setToast('Создана копия расчёта. Тариф и размещение пересчитаны.');}
 function applyOption(o:ConsolidationOption){update(d=>({...d,selected:o.cargo.map(c=>c.id),vehicleId:o.vehicle.id,manual:null}));setPendingOption(o);navigate(1);setToast('Заявки добавлены в расчёт. Сохраните рейс, чтобы учесть экономию.');}
 const cargoView=data.cargo.filter(c=>(!onlySelected||page!==1||data.selected.includes(c.id))&&[c.name,c.requestId,c.origin,c.destination,c.customer].some(s=>s.toLowerCase().includes(search.toLowerCase())));
 const historyView=data.history.filter(h=>(historyFilter==='all'||(historyFilter==='fit'?h.result.fits:historyFilter==='fail'?!h.result.fits:h.demo))&&(!historyFrom||h.date.slice(0,10)>=historyFrom)&&(!historyTo||h.date.slice(0,10)<=historyTo)&&[h.id,h.vehicle.name,...h.cargo.map(c=>c.requestId)].some(s=>s.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='cost'?b.cost-a.cost:sort==='load'?b.result.utilization-a.result.utilization:sort==='old'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));
 const searchBox=<TextField size="small" placeholder="Поиск по названию, заявке или маршруту" value={search} onChange={e=>setSearch(e.target.value)} className="search-input" slotProps={{input:{startAdornment:<Search size={16} style={{marginRight:8,color:'#93a2a6'}}/>},htmlInput:{'aria-label':'Поиск'}}}/>;
 const heading=(title:string,subtitle:string,actions?:React.ReactNode)=><div className="page-heading"><div><div className="eyebrow">LOGISTICS LOAD PLANNER</div><h1>{title}</h1><p>{subtitle}</p></div><div className="actions">{actions}</div></div>;
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_current_loading_calculation',description:'Read selected cargo, vehicle, physical loading result and estimated cost.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {vehicle:vehicle.name,cargo:selected.map(c=>({name:c.name,quantity:c.quantity})),fits:result.fits,reasons:result.reasons,utilization:result.utilization,cost};}},{signal:controller.signal})).catch(()=>{});return ()=>controller.abort();},[vehicle,selected,result,cost]);
 return <div className="app"><aside><div className="brand"><Truck/><div>LOAD PLANNER<small>ЛОГИСТИКА И ТРАНСПОРТ</small></div></div><div className="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav>{navigation.map((n,i)=>{const Icon=navIcons[i];return <button className={page===i?'active':''} key={n} onClick={()=>navigate(i)}><Icon size={18}/>{n}{i===5&&options.length>0&&<span className="nav-count">{options.length}</span>}</button>})}</nav><div className="sidebar-bottom"><span className="online"/>{data.settings.company}<small>Данные сохраняются в этом браузере</small></div></aside><main><header><span>Рабочее пространство <span className="muted">/ {navigation[page]}</span></span><div className="header-right"><span>{new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</span><span className="avatar">ЛО</span></div></header><div className="content">{storageError&&<Alert severity="warning" className="mb">{storageError}</Alert>}
 {(page===0||page===8)&&<Dashboard data={data} options={options} analytics={page===8} onNavigate={navigate}/>}
 {(page===1||page===4)&&<>{heading(page===1?'Новый расчёт':'Схема загрузки','Калькулятор загрузки и консолидации ТМЗ',<><Button startIcon={<Download size={16}/>} onClick={()=>exportCalculation(snapshot(),options)}>Excel</Button><Button startIcon={<Printer size={16}/>} onClick={()=>window.print()}>Печать</Button><Button variant="contained" startIcon={<Save size={16}/>} onClick={saveCalculation}>Сохранить расчёт</Button></>)}<div className="calculation-layout"><div className="calculation-main"><section className="panel"><div className="panel-heading"><h2>01 <span className="step-title">Транспорт и маршрут</span></h2><span className="subtle-chip">Автоматический расчёт</span></div><div className="vehicle-select"><TextField select label="Выберите автомобиль" value={vehicle.id} size="small" onChange={e=>{if(e.target.value==='custom'){setEditor({kind:'vehicle',value:{...vehicle,id:uid(),name:'Пользовательский автомобиль'}});return;}mutate(d=>({...d,vehicleId:e.target.value}));}}>{data.vehicles.map(v=><MenuItem key={v.id} value={v.id}>{v.name}</MenuItem>)}<MenuItem value="custom">＋ Пользовательский автомобиль</MenuItem></TextField><TextField label="Расстояние маршрута, км" type="number" size="small" value={data.settings.distance} slotProps={{htmlInput:{min:0}}} onChange={e=>{const n=Number(e.target.value);if(n>=0&&Number.isFinite(n))mutate(d=>({...d,settings:{...d.settings,distance:n}}));}}/></div><div className="vehicle-details"><span>{fmt(vehicle.length)} × {fmt(vehicle.width)} × {fmt(vehicle.height)} м</span><span>{fmt(vehicle.length*vehicle.width*vehicle.height,2)} м³</span><span>до {fmt(vehicle.capacity)} кг</span><span>{fmt(vehicle.maxFloorLoad)} кг/м²</span></div><div className="actions"><Button variant="outlined" startIcon={<Sparkles size={16}/>} onClick={()=>chooseVehicle('cost')} disabled={!selected.length}>Подобрать оптимальный транспорт</Button><Button onClick={()=>chooseVehicle('size')} disabled={!selected.length}>Минимальный по размеру</Button></div>{new Set(selected.map(c=>`${c.origin}|${c.destination}|${c.date}`)).size>1&&!applicable&&<Alert severity="info" className="mt">Выбраны разные маршруты или даты. Проверяется совместная вместимость; стоимость предварительная по первой позиции. Для совместимого рейса используйте «Консолидацию».</Alert>}{applicable&&<Alert severity="success" className="mt">Консолидация №{applicable.requests.join(' + ')} · экономия {money(applicable.savings)} · {fmt(applicable.distance)} км</Alert>}</section>
 {page===1&&<section className="panel table-panel"><div className="panel-heading"><h2>02 <span className="step-title">Грузовые места</span> <span className="count-chip">{selected.length}</span></h2><div className="actions"><Button size="small" startIcon={<Upload size={15}/>} onClick={()=>excelInput.current?.click()}>Импорт Excel</Button><Button size="small" variant="contained" startIcon={<Plus size={15}/>} onClick={newCargo}>Добавить ТМЗ</Button></div></div><div className="toolbar">{searchBox}<FormControlLabel control={<Checkbox size="small" checked={onlySelected} onChange={e=>setOnlySelected(e.target.checked)}/>} label="Только выбранные"/><Button size="small" onClick={()=>mutate(d=>({...d,selected:cargoView.every(c=>d.selected.includes(c.id))?d.selected.filter(id=>!cargoView.some(c=>c.id===id)):[...new Set([...d.selected,...cargoView.map(c=>c.id)])]}))}>Выбрать / снять все</Button></div><CargoTable cargo={cargoView} selected={data.selected} onToggle={id=>mutate(d=>({...d,selected:d.selected.includes(id)?d.selected.filter(x=>x!==id):[...d.selected,id]}))} onEdit={editCargo} onDelete={deleteCargo} onCopy={copyCargo} onQuantity={(c,n)=>mutate(d=>({...d,cargo:d.cargo.map(x=>x.id===c.id?{...x,quantity:n}:x)}))}/><div className="table-footer"><span>{selected.length} позиций · {result.count} мест</span><strong>{fmt(result.volume)} м³ · {fmt(result.weight)} кг</strong></div></section>}
 <LoadingPlan cargo={selected} vehicle={vehicle} positions={result.positions} onChange={p=>update(d=>({...d,manual:p}))} onReset={()=>update(d=>({...d,manual:null}))}/><section className="panel"><h2>Площадь и штабелирование</h2><div className="facts-grid"><div><span>Без штабелирования</span><strong>{fmt(result.rawFloor)} м²</strong></div><div><span>Теоретический минимум</span><strong>{fmt(result.effectiveFloor)} м²</strong></div><div><span>Размещено на полу</span><strong>{fmt(result.floor)} м²</strong></div><div><span>Не размещено</span><strong>{result.unplaced} мест</strong></div></div></section>
 {(picked||!result.fits)&&selected.length>0&&<section className="panel table-panel"><div className="panel-heading"><h2>Сравнение автомобилей</h2></div><div className="table-scroll"><table><thead><tr><th>Автомобиль</th><th>Результат / причины</th><th>Загрузка</th><th>Стоимость</th><th/></tr></thead><tbody>{comparisons.map(x=><tr key={x.vehicle.id}><td><strong>{x.vehicle.name}</strong></td><td><span className={`status ${x.result.tone}`}>{x.result.fits?'Подходит':'Не подходит'}</span>{!x.result.fits&&<small>{x.result.reasons.join('; ')}</small>}</td><td>{fmt(x.result.utilization)}%</td><td>{money(x.cost)}</td><td><Button size="small" onClick={()=>mutate(d=>({...d,vehicleId:x.vehicle.id}))}>Выбрать</Button></td></tr>)}</tbody></table></div><p className="footnote">Рекомендуется: {comparisons.find(x=>x.result.fits)?.vehicle.name??'подходящий автомобиль не найден'}. Приоритет: вместимость, стоимость, близость загрузки к 80%.</p></section>}</div><Summary result={result} vehicle={vehicle} cost={cost}/></div></>}
 {page===2&&<>{heading('Справочник ТМЗ','Габариты, вес и условия размещения каждого грузового места.',<><Button startIcon={<Download size={16}/>} onClick={()=>exportCargo(data.cargo)}>Экспорт Excel</Button><Button startIcon={<Upload size={16}/>} onClick={()=>excelInput.current?.click()}>Импорт Excel</Button><Button variant="contained" startIcon={<Plus size={16}/>} onClick={newCargo}>Добавить ТМЗ</Button></>)}<section className="panel table-panel"><div className="toolbar">{searchBox}<span className="subtle-chip">{data.cargo.length} позиций</span></div><CargoTable cargo={cargoView} onEdit={editCargo} onDelete={deleteCargo} onCopy={copyCargo}/></section><p className="footnote">Заявки формируются по номеру. Для одной заявки задавайте одинаковые маршрут и дату. Импорт атомарный: при ошибке строки данные не добавляются. Экспорт служит шаблоном для импорта.</p></>}
 {page===3&&<>{heading('Автомобили','Внутренние размеры кузова и ограничения транспорта.',<Button variant="contained" startIcon={<Plus size={16}/>} onClick={()=>setEditor({kind:'vehicle',value:{...vehicle,id:uid(),name:'Новый автомобиль',description:''}})}>Добавить автомобиль</Button>)}<div className="vehicle-grid">{data.vehicles.map(v=><section className="panel vehicle-card" key={v.id}><div className="panel-heading"><div className="vehicle-icon"><Truck size={29}/></div><span className="subtle-chip">{fmt(v.capacity/1000)} т</span></div><h2>{v.name}</h2><p>{v.description}</p><div className="vehicle-dim">{fmt(v.length)} <span>×</span> {fmt(v.width)} <span>×</span> {fmt(v.height)} <small>м</small></div><dl><div><dt>Полезный объём</dt><dd>{fmt(v.length*v.width*v.height,2)} м³</dd></div><div><dt>Площадь пола</dt><dd>{fmt(v.length*v.width)} м²</dd></div><div><dt>Нагрузка на пол</dt><dd>{fmt(v.maxFloorLoad)} кг/м²</dd></div><div><dt>Стоимость рейса</dt><dd>{money(v.tripCost)}</dd></div><div><dt>За км / минимум</dt><dd>{money(v.perKm)} / {money(v.minimum)}</dd></div></dl><div className="actions"><Button size="small" startIcon={<Pencil size={14}/>} onClick={()=>setEditor({kind:'vehicle',value:v})}>Изменить</Button><Button size="small" onClick={()=>{mutate(d=>({...d,vehicleId:v.id}));navigate(1)}}>В расчёт</Button><IconButton aria-label={`Удалить ${v.name}`} disabled={data.vehicles.length===1} size="small" onClick={()=>setConfirm({title:`Удалить ${v.name} и связанные тарифы? История останется.`,action:()=>mutate(d=>({...d,vehicles:d.vehicles.filter(x=>x.id!==v.id),tariffs:d.tariffs.filter(t=>t.vehicleId!==v.id),vehicleId:d.vehicleId===v.id?d.vehicles.find(x=>x.id!==v.id)!.id:d.vehicleId}))})}><Trash2 size={15}/></IconButton></div></section>)}</div></>}
 {page===5&&<>{heading('Консолидация заявок','Один рейс. Совместимые грузы. Меньше затрат.',<Button variant="contained" startIcon={<Sparkles size={17}/>} onClick={()=>setToast(`Найдено ${options.length} выгодных вариантов по текущим данным`)}>Найти варианты консолидации</Button>)}<section className="panel"><div className="settings-inline">{(['dateTolerance','maxDeviation','distance'] as const).map((key,i)=><TextField key={key} label={['Совместимость дат, дней','Отклонение, км','Базовый путь, км'][i]} size="small" type="number" value={data.settings[key]} slotProps={{htmlInput:{min:0,step:key==='dateTolerance'?1:'any'}}} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&(key!=='dateTolerance'||Number.isInteger(n)))mutate(d=>({...d,settings:{...d.settings,[key]:n}}))}}/>)}</div><p className="footnote">Проверяются пары и тройки заявок. Это альтернативы, а не готовый график. Расстояние задаётся вручную. Близкие города — из настроек. Заявки с разными маршрутами внутри одного номера исключаются.</p></section><div className="option-list">{options.map((o,i)=><section className="panel option-card" key={o.id}><div className="option-rank">{String(i+1).padStart(2,'0')}</div><div className="option-body"><div className="panel-heading"><div><h2>Заявки №{o.requests.join(' + №')}</h2><p className="panel-subtitle">{o.route} · {o.vehicle.name}</p></div><span className={`status ${o.result.tone}`}>{fmt(o.result.utilization)}% · {o.result.status}</span></div><div className="option-values"><div><span>Отдельные рейсы</span><strong>{money(o.separate)}</strong></div><div><span>Один автомобиль</span><strong>{money(o.cost)}</strong></div><div className="saving"><span>Экономия {fmt(o.savingsPercent,0)}%</span><strong>{money(o.savings)}</strong></div><Button variant={i===0?'contained':'outlined'} endIcon={<ArrowRight size={15}/>} onClick={()=>applyOption(o)}>В расчёт</Button></div><div className="option-meta">{o.result.count} мест · {fmt(o.result.weight/1000)} т · {fmt(o.result.volume)} м³ · {fmt(o.result.floor)} м² · {fmt(o.distance)} км · {money(o.cost/o.result.weight)} / кг</div></div></section>)}</div>{!options.length&&<section className="panel empty"><Combine size={32}/><h2>Выгодные варианты не найдены</h2><p>Проверьте отправление, совместимость дат, тарифы и габариты грузов.</p><Button onClick={()=>navigate(2)}>Открыть ТМЗ</Button></section>}</>}
 {page===6&&<>{heading('Тарифы перевозчиков','Стоимость = max(минимум, фиксированная часть + цена за км × расстояние).',<Button variant="contained" startIcon={<Plus size={16}/>} onClick={()=>setEditor({kind:'tariff',value:{id:uid(),carrier:'',origin:'Алматы',destination:'Астана',vehicleId:vehicle.id,fixed:0,perKm:0,minimum:0,validFrom:today()}})}>Добавить тариф</Button>)}<section className="panel table-panel"><div className="toolbar">{searchBox}</div><div className="table-scroll"><table><thead><tr><th>Перевозчик</th><th>Направление</th><th>Автомобиль</th><th>Фиксированно</th><th>За км</th><th>Минимум</th><th>Действует с</th><th/></tr></thead><tbody>{data.tariffs.filter(t=>[t.carrier,t.origin,t.destination].some(s=>s.toLowerCase().includes(search.toLowerCase()))).map(t=><tr key={t.id}><td><strong>{t.carrier}</strong></td><td>{t.origin} → {t.destination}</td><td>{data.vehicles.find(v=>v.id===t.vehicleId)?.name}</td><td>{money(t.fixed)}</td><td>{money(t.perKm)}</td><td>{money(t.minimum)}</td><td>{t.validFrom}</td><td><div className="row-actions"><IconButton aria-label={`Изменить тариф ${t.carrier}`} onClick={()=>setEditor({kind:'tariff',value:t})}><Pencil size={15}/></IconButton><IconButton aria-label={`Удалить тариф ${t.carrier}`} onClick={()=>setConfirm({title:'Удалить тариф?',action:()=>mutate(d=>({...d,tariffs:d.tariffs.filter(x=>x.id!==t.id)}))})}><Trash2 size={15}/></IconButton></div></td></tr>)}</tbody></table>{!data.tariffs.length&&<div className="empty">Нет тарифов. Применяются цены автомобилей.</div>}</div></section><p className="footnote">Для перевозчика берётся последняя действующая версия на дату отправки, затем выбирается минимальная стоимость. Если тарифа на маршрут нет, используются цены автомобиля.</p></>}
 {page===7&&<>{heading('История расчётов','Сохранённые снимки груза, транспорта, размещения и стоимости.',<Button onClick={()=>setConfirm({title:'Удалить демонстрационные расчёты?',action:()=>update(d=>({...d,history:d.history.filter(h=>!h.demo)}))})}>Удалить демо-историю</Button>)}<section className="panel table-panel"><div className="toolbar">{searchBox}<TextField select label="Статус" size="small" value={historyFilter} onChange={e=>setHistoryFilter(e.target.value)}><MenuItem value="all">Все</MenuItem><MenuItem value="fit">Загрузка возможна</MenuItem><MenuItem value="fail">Не влезает</MenuItem><MenuItem value="demo">Демонстрационные</MenuItem></TextField><TextField select label="Сортировка" size="small" value={sort} onChange={e=>setSort(e.target.value)}><MenuItem value="new">Сначала новые</MenuItem><MenuItem value="old">Сначала старые</MenuItem><MenuItem value="cost">По стоимости</MenuItem><MenuItem value="load">По загрузке</MenuItem></TextField><TextField label="С даты" type="date" size="small" value={historyFrom} onChange={e=>setHistoryFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField label="По дату" type="date" size="small" value={historyTo} onChange={e=>setHistoryTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/></div><div className="table-scroll"><table><thead><tr><th>Расчёт / дата</th><th>Заявки</th><th>Автомобиль</th><th>Груз</th><th>Загрузка</th><th>Стоимость / экономия</th><th/></tr></thead><tbody>{historyView.map(h=><tr key={h.id}><td><strong>{h.id}</strong><small>{new Date(h.date).toLocaleString('ru-RU')}</small>{h.demo&&<small>Демонстрационный</small>}</td><td>№{[...new Set(h.cargo.map(c=>c.requestId))].join(', №')}</td><td>{h.vehicle.name}</td><td>{fmt(h.result.weight)} кг<small>{fmt(h.result.volume)} м³</small></td><td><span className={`status ${h.result.tone}`}>{fmt(h.result.utilization,0)}%</span><small>{h.result.status}</small></td><td><strong>{money(h.cost)}</strong><small className="green-text">−{money(h.savings)}</small></td><td><div className="row-actions"><IconButton aria-label={`Копировать расчёт ${h.id}`} title="Копировать в новый расчёт" onClick={()=>loadHistory(h)}><Copy size={15}/></IconButton><IconButton aria-label={`Экспорт ${h.id}`} title="Экспорт Excel" onClick={()=>exportCalculation(h,[])}><Download size={15}/></IconButton><IconButton aria-label={`Удалить ${h.id}`} title="Удалить" onClick={()=>setConfirm({title:`Удалить расчёт ${h.id}?`,action:()=>update(d=>({...d,history:d.history.filter(x=>x.id!==h.id)}))})}><Trash2 size={15}/></IconButton></div></td></tr>)}</tbody></table>{!historyView.length&&<div className="empty">Расчёты не найдены</div>}</div></section></>}
 {page===9&&<>{heading('Настройки','Параметры рабочего пространства и резервное копирование.')}<SettingsPage data={data} update={mutate} restore={()=>backupInput.current?.click()}/></>}
 <footer>Logistics Load Planner <span>Калькулятор загрузки и консолидации ТМЗ · ₸ / м / кг</span></footer></div></main>
 <input ref={excelInput} type="file" accept=".xlsx" hidden onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const rows=parseExcel(await file.arrayBuffer());mutate(d=>({...d,cargo:[...d.cargo,...rows],selected:page===1?[...d.selected,...rows.map(c=>c.id)]:d.selected}));setToast(`Импортировано ${rows.length} позиций`);}catch(e){setToast(`Ошибка импорта: ${(e as Error).message}`)}}}/>
 <input ref={backupInput} type="file" accept=".json" hidden onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const restored=JSON.parse(await file.text());if(!validateData(restored))throw Error('Неверная структура резервной копии');setConfirm({title:'Заменить текущие данные резервной копией? Сначала сохраните текущую копию, если она нужна.',action:()=>{setPendingOption(null);update(()=>restored);setToast('Резервная копия восстановлена');}});}catch(e){setToast((e as Error).message)}}}/>
 {editor&&<Editor key={editor.value.id} title={editor.kind==='cargo'?'Параметры ТМЗ':editor.kind==='vehicle'?'Параметры автомобиля':'Тариф перевозчика'} value={editor.value} fields={editor.kind==='cargo'?cargoFields:editor.kind==='vehicle'?vehicleFields:tariffFields} validate={editor.kind==='cargo'?validateCargo:editor.kind==='vehicle'?validateVehicle:undefined} onClose={()=>setEditor(null)} onSave={saveEditor}/>}
 {confirm&&<Dialog open onClose={()=>setConfirm(null)}><DialogTitle>Подтвердите действие</DialogTitle><DialogContent>{confirm.title}</DialogContent><DialogActions><Button onClick={()=>setConfirm(null)}>Отмена</Button><Button color="error" onClick={()=>{confirm.action();setConfirm(null)}}>Подтвердить</Button></DialogActions></Dialog>}
 <Snackbar open={!!toast} autoHideDuration={7000} onClose={()=>setToast('')} message={toast} action={<Button color="inherit" onClick={()=>setToast('')}>Закрыть</Button>}/></div>;
}
